[package]
name = "nezuo/subject"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["wally.toml", "src", "src/init.lua", "default.project.json"]
exclude = ["*"]

[dependencies]
TestEZ = "roblox/testez@0.4.1"